spring:
  datasource:
    url: jdbc:postgresql://metro.proxy.rlwy.net:44366/railway
    username: postgres
    password: mjoCjJNoUCCPrkjZzfLhVZQynhlhPfLs
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate