spring:
  profiles:
    active: prod
  # config:
  #   activate:
  #     on-profile: prod  # Ou o nome do perfil que você usa para produção

  datasource:
    url: jdbc:postgresql://metro.proxy.rlwy.net:44366/railway
    username: postgres
    password: mjoCjJNoUCCPrkjZzfLhVZQynhlhPfLs
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
